# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'feature/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  checks: write

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo test départ,
          echo test, ajout.
